
// Generated by Cadence Genus(TM) Synthesis Solution 19.12-s121_1
// Generated on: Oct 16 2021 23:42:22 IST (Oct 16 2021 18:12:22 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, count);
  input clk, rst;
  output [2:0] count;
  wire clk, rst;
  wire [2:0] count;
  wire n_1, n_3, n_4, n_5, n_6, n_9, n_10;
  DFCQM2RA \count_reg[1] (.CKB (clk), .D (n_6), .Q (count[1]));
  DFCQM2RA \count_reg[0] (.CKB (clk), .D (n_5), .Q (count[0]));
  DFCQM2RA \count_reg[2] (.CKB (clk), .D (n_3), .Q (count[2]));
  NR3B1M2R g98(.B (n_10), .C (n_4), .NA (n_9), .Z (n_6));
  NR2M2R g96(.A (count[0]), .B (n_4), .Z (n_5));
  NR2M2R g97(.A (n_1), .B (n_4), .Z (n_3));
  OAI21B20M2R g99(.B (rst), .NA1 (count[2]), .NA2 (n_10), .Z (n_4));
  MAOI22M2RA g100(.A1 (n_9), .A2 (count[2]), .B1 (n_9), .B2 (count[2]),
       .Z (n_1));
  ADCSIOM2R g2(.A (count[1]), .B (count[0]), .CO0B (n_9), .CO1B (n_10));
endmodule

